### PR TITLE
Add Catalan (Spain) translation

### PR DESCRIPTION
**Pull request by fsdevlondon**
I'm a native speaker, so it was a handmade job. I hope this will help you expand more the product.

### CODE REVIEW

**Comment by MrPolymath** [comment]
Isn't there a lot of stuff missing? I've checked at the original en.json and there is a lot more variables now. I'm also a native catalan speaker. I can help if someone confirms my hypothesis. Thank you!

**Comment by fsdevlondon** [comment]
Is only missing the "_desc", you do not need to translate them. The "en" file looks that has not been changed from in one month, so I hope we do not have new ones. Thanks!

**Comment by MrPolymath** [comment]
Okey I get it. I've tried the Spanish translation and when I got asked, in spanish, "Who you are? (select for now, you can change it later)", I didn't know what to answer. In the english one, you have two buttons so there is no need for translation, but here I was lost (Checking the translation files I figured out what to answer). I guess without a description some answers might not be obvious. Why aren't _desc translated too?

**Comment by fsdevlondon** [comment]
Please read the instructions that the owner has put before to continue this conversation. 
https://github.com/ro31337/libretaxi/blob/master/doc/TRANSLATE.md

**Pull request closed without merging**
