### PR TITLE
Adding arabic localization

### PR DESCRIPTION
**Pull request by maysara**
I've added the localized strings and added entry in supported locales

### CODE REVIEW

**Comment by ro31337** [comment]
Thanks, I'll fix some bugs (failing tests) and will integrate Arabic today or tomorrow

**Comment by ro31337** [comment]
Looks great, thanks! Will deploy later today.

**Comment by maysara** [comment]
Great, please let us know when its deployed/visible on telegram libretaxi_bot or if one needs to do something to make it show up

**Comment by ro31337** [comment]
deployed, thanks!

**Comment by ro31337** [comment]
Also, it's on the last page (when you select the language). You can move it
to the first or second page.

**Pull request merged**
