### PR TITLE
Update fa.json

### PR DESCRIPTION
**Pull request by paradox70**
I try to fix and modify all the improvements this persian translation has needed.
A few lines needed to change direction from LTR to RTL and now I hope everything works in perfect mode.

### CODE REVIEW

**Comment by ro31337** [comment]
Sounds good. thanks! Does this fix includes removing the need to check-in every hour?

**Comment by paradox70** [comment]
Yes, that's included.

**Comment by ro31337** [comment]
Thanks, PR merged. Will deploy later today

**Comment by paradox70** [comment]
Not at all.
Thank you.

**Comment by ro31337** [comment]
(Deployed)

**Pull request merged**
