### PR TITLE
editing getting started page

### PR DESCRIPTION
**Pull request by fatcatdog**
editing getting started page

### CODE REVIEW

**Comment by ro31337** [comment]
Thanks!

**Comment by fatcatdog** [comment]
No problem, thanks for LibreTaxi,

To build my Telegram Bot, do you have any recommended resources on how to
build the bot?

Jake
Fatcatdog

**Comment by ro31337** [comment]
what do you mean by saying "build"?

**Comment by fatcatdog** [comment]
as of now I see my telegram cli server receiving messages from user, but I
don't know how to make bot respond to user?

**Comment by ro31337** [comment]
Hm... do you see any errors in console? Can you post logs, screenshots?

**Comment by fatcatdog** [comment]
Submitted a new Github issue

Best,
Jake

**Pull request merged**
