### PR TITLE
#485 Languages paging, confirmation, French, German

### PR DESCRIPTION
**Pull request by ro31337**

### CODE REVIEW

**Comment by Apercu** [comment]
Why are you not merging PRs normally? This is overriding commit authors..

**Comment by ro31337** [comment]
Merged. To be deployed at 7AM PST.

**Comment by Apercu** [comment]
👎  @ro31337 You are taking attribution of other people work by batching their changes into separate branches and rebasing under **YOUR** name, rather than squashing/merging and keeping original commit authors. Do you even Github? Disgusting.

**Comment by ro31337** [comment]
@Apercu 

> You are taking attribution of other people work by batching their changes into separate branches and rebasing under YOUR name

This was done automatically on GitHub because of my settings. I always prefer to squash to keep commit history clean. However, for me it's not important. I switched this feature off. I appreciate your contribution, the way you communicate, and looking forward to work with you in the future.

**Comment by Apercu** [comment]
screen
What's the issue with this button? Do you find it more difficult to click on it rather than rebasing manually onto separate branches and creating new PRs?

**Comment by ro31337** [comment]
Process and contribution notes have been updated. Didn't mean to hurt anyone. I don't want to explain how exactly it has happened and how exactly my development environment works and configured and why (it will probably take a while), because it has been already changed. I never had this in mind ("taking attribution of other people"), some of other previously merged commits can confirm that. Sorry this has happened too you. I appreciate everyone's work and offered solutions to resolve disrespect (if any) in some PRs where these changes have been made.

**Comment by Apercu** [comment]
It actually didn't even happened to me, I was just helping with the french translation stuff, and noticed this kinda odd thing. Props to you for changing this in the future though, it's hard to recognize your mistakes.

**Pull request merged**
