### PR TITLE
Replace deprecated 'node-uuid' package with 'uuid'

### PR DESCRIPTION
**Pull request by rikelme**

### CODE REVIEW

**Comment by ro31337** [comment]
closed? It's ok to merge IMO.

**Comment by rikelme** [comment]
yeah, I closed it to figure out how to match the branch prefix with the pull request number :)

**Comment by rikelme** [comment]
ping

**Comment by ro31337** [comment]
Can you please give me a little bit of background why it is important? When I look a the current package I see huge amount of downloads from npmjs every day.

Thank you!

**Comment by rikelme** [comment]
'npm install' warned that 'node-uuid' is a deprecated package. I strive to have warn-free build logs and get rid of deprecated APIs, packages, etc.
In addition, README says that libretaxi has a pretty high bar for code quality, so I figured you would appreciate the patch.
That's all :)

**Comment by ro31337** [comment]
Thank you! Merged!

**Pull request merged**
